### ISSUE TITLE
similar list which might be partly of interest

### ISSUE THREAD

**Issue by wiesehahn** [Nowosad/conferences_2025#4]
Hey Jakub, 

I maintain a similar list with conferences etc which are of interest to me (mainly geospatial, remote sensing, forestry), and I just added it to github. 
Not sure what might be of interest for you but you can have a look at it and see if you want to add something to your list.

https://github.com/wiesehahn/conferences

**Comment by Nowosad** [comment]
Great -- thanks for sharing the list!
